# src/backend/optimizer/cascades/Makefile

subdir = src/backend/optimizer/cascades
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = cascades.o memo.o task.o rule.o property.o \
       pg_adapter.o planbuild.o debug.o

include $(top_srcdir)/src/backend/common.mk
