#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for optimizer/cascades/reorder
#
#-------------------------------------------------------------------------

subdir = src/backend/optimizer/cascades/reorder
top_builddir = ../../../../..
include $(top_builddir)/src/Makefile.global

OBJS = multijoin.o joinorder.o dp_enum.o

include $(top_srcdir)/src/backend/common.mk
